- libs/blog/partners/ui-partners/src/lib/partners-list/partners-list.component.html
- libs/blog/partners/ui-partners/src/lib/partners-list/partners-list.component.scss
- libs/blog/partners/ui-partners/src/lib/partners-list/partners-list.component.ts
Changed:
-styles for desktop view
-NgOptimisedImage Directive
Deleted:
-style file
> style(partners-list): changed layout for desktop view, appended ngOptmisedImage directive

- libs/blog/authors/ui-author-info/src/lib/author-info/author-info-template.component.ts
- libs/blog/authors/ui-author-info/src/lib/author-info/author-info.component.html
- libs/blog/authors/ui-author-info/src/lib/author-info/author-info.component.ts
- libs/blog/authors/ui-author-info/src/lib/author-info/author-info.stories.ts
> style(author-info): style adjustments and clampText property

- libs/blog/become-author/feature-become-author-page/src/lib/become-author-page/become-author-page.component.html
- libs/blog/become-author/feature-become-author-page/src/lib/become-author-page/become-author-page.component.spec.ts
- libs/blog/become-author/feature-become-author-page/src/lib/become-author-page/become-author-page.component.ts
- libs/blog/become-author/feature-become-author-page/src/lib/components/become-author-advertisement/become-author-advertisement.component.html
- libs/blog/become-author/feature-become-author-page/src/lib/components/become-author-advertisement/become-author-advertisement.component.spec.ts
- libs/blog/become-author/feature-become-author-page/src/lib/components/become-author-advertisement/become-author-advertisement.component.ts
- libs/blog/become-author/feature-become-author-page/src/lib/components/become-author-benefits/become-author-benefits.component.html
- libs/blog/become-author/feature-become-author-page/src/lib/components/become-author-improvements/become-author-improvements.component.html
Appended:
-become author advertisement component
Modified:
-become author page
> feat(become-author-advertisement): created advertisemet component, changed layout become author page

- libs/blog/layouts/ui-navigation/src/lib/navigation/navigation.component.ts
Fixed:
Link in become an author
> fix(navigation-component): appended-nav-link

- libs/blog/articles/ui-article-card/src/lib/components/article-regular-card/article-regular-card.component.html
- libs/blog/become-author/feature-become-author-page/src/lib/components/become-author-advertisement/become-author-advertisement.component.html
- libs/blog/become-author/feature-become-author-page/src/lib/components/become-author-benefits/become-author-benefits.component.html
- libs/blog/become-author/feature-become-author-page/src/lib/components/become-author-improvements/become-author-improvements.component.html
> style(article-regular-card): changed-line-clamp

- libs/blog/articles/ui-table-of-contents/src/lib/table-of-contents/table-of-contents.component.html
> style(client): lower font for items in table of contents

- libs/blog/become-author/feature-become-author-page/src/lib/become-author-page/become-author-page.component.html
Changed:
-gap betweeen page and footer
> style(become-an-author): gap between page and footer altered

- libs/blog-bff/articles/api/src/lib/mappers.ts
- libs/blog-contracts/articles/src/lib/articles.ts
- libs/blog/articles/feature-article/src/lib/article-details/article-details.component.html
- libs/blog/articles/feature-article/src/lib/article-details/article-details.component.ts
- libs/blog/articles/feature-article/src/lib/article-share-icons/article-share-icons.component.ts
- libs/blog/articles/ui-table-of-contents/src/lib/table-of-contents/table-of-contents.component.html
- libs/blog/shared/ui-card/src/lib/card.component.ts
> feat(client): share article

- libs/blog/layouts/ui-navigation/src/lib/navigation/navigation.component.html
- libs/blog/layouts/ui-navigation/src/lib/navigation/navigation.component.ts
Changes:
-conditional routerLink directive and href attribute
> fix(navigation-component): conditional routerLink directive and href attribute

- libs/blog-bff/articles/api/src/lib/mappers.ts
- libs/blog-bff/articles/api/src/lib/utils.ts
- libs/blog/articles/feature-latest-articles/src/lib/feature-latest-articles/feature-latest-articles.component.html
- libs/blog/authors/ui-author-card/src/lib/author-card/author-card.component.html
- libs/blog/become-author/feature-become-author-page/src/lib/become-author-page/become-author-page.component.html
- libs/blog/home/feature-home/src/lib/home-page/home-page.component.html
- libs/blog/newsletter/feature-newsletter/src/lib/feature-newsletter/newsletter.component.html
Tool used: https://chromewebstore.google.com/detail/siteimprove-accessibility/djcglbmbegflehmbfleechkjhmedcopn?hl=pl
> feat(a11y): increased a11y globally

- libs/blog/shared/ui-pagination/src/lib/pagination/pagination.component.html
- libs/blog/shared/ui-pagination/src/lib/pagination/pagination.component.ts
Changed:
-buttons hidden when current page is equal to start or last number
> fix(pagination): buttons hidden conditionally

- libs/blog-bff/articles/api/src/lib/api.ts
- libs/blog-bff/authors/api/src/lib/api.ts
- libs/blog-bff/shared/util-middleware/src/index.ts
- libs/blog-bff/shared/util-middleware/src/lib/cache.ts
- libs/blog-bff/shared/util-middleware/src/lib/lang.ts
- libs/blog-bff/shared/util-wp/src/index.ts
- libs/blog-bff/shared/util-wp/src/lib/lang-utils.ts
- libs/shared/utils-i18n/src/lib/utils.ts
blocked by
- https://github.com/HouseOfAngular/angular-love/pull/173
> refactor(bff): middlewares usage

- apps/blog/project.json
- apps/blog/src/app/app.config.ts
> feat(client): enable zoneless cd

- libs/blog/newsletter/feature-newsletter/src/lib/feature-newsletter/newsletter.component.html
> fix(newsletter-card): input styles fixed

- libs/blog/articles/feature-guides/src/lib/feature-guides/feature-guides.component.html
- libs/blog/articles/feature-latest-articles/src/lib/latest-articles-page/latest-articles-page.component.html
- libs/blog/articles/feature-news/src/lib/feature-news/feature-news.component.html
- libs/blog/articles/feature-recommended-articles/src/lib/recommended-articles/recommended-articles.component.html
- libs/blog/authors/feature-author/src/lib/feature-author/feature-author.component.html
- libs/blog/layouts/ui-layouts/src/lib/layout/layout.component.html
- libs/blog/search/feature-search-results-page/src/lib/search-results-page/search-results-page.component.html
- libs/blog/shared/ui-pagination/src/lib/pagination/pagination.component.html
- libs/blog/shared/ui-pagination/src/lib/pagination/pagination.component.ts
> fix(client): pagination mobile ui

- libs/blog/layouts/ui-layouts/src/lib/header/header.component.html
Changed:
-button size for mobile devices
> fix(header-component): fixed navigation for mobile devices

- libs/blog/articles/ui-article-list-title/src/lib/ui-article-list-title/ui-article-list-title.component.html
Appended:
-line clamp and max-width for mobile devices
> fix(article-list-title): mobile devices fix title

- libs/blog/about-us/feature-about-us/src/lib/feature-about-us/feature-about-us.component.html
Fixed:
-description in about us section (mobile devices)
> fix(about-us-component): fix description for mobile devices

- apps/blog/src/assets/i18n/en.json
- apps/blog/src/assets/i18n/pl.json
- libs/blog/newsletter/data-access/src/lib/state/newsletter.store.ts
- libs/blog/newsletter/feature-newsletter/src/lib/feature-newsletter/newsletter.component.html
- libs/blog/newsletter/feature-newsletter/src/lib/feature-newsletter/newsletter.component.ts
Appended:
-translations
-error card to handle with error state
> feat(newsletter-card): error state handling

- apps/blog/src/assets/i18n/en.json
- apps/blog/src/assets/i18n/pl.json
- libs/blog/ad-banner/data-access/src/lib/infrastructure/ad-banner.service.ts
- libs/blog/ad-banner/data-access/src/lib/state/ad-banner.store.ts
- libs/blog/ad-banner/ui/src/lib/ad-banner/ad-banner.component.html
- libs/blog/ad-banner/ui/src/lib/ad-banner/ad-banner.component.ts
Changed:
-styles (mobile device supported)
-data model
> fix(ad-banner): changed styles and ad banner model

- apps/blog/src/assets/i18n/pl.json
- libs/blog/shared/ui-difficulty/src/lib/ui-difficulty.component.ts
Changed:
-`al-difficulty` component styles
Appended:
-level translations
> feat(ui-difficulty-component): translations appended, changed in styles for mobile devices

- libs/blog/search/data-access/src/lib/models/search.ts
- libs/blog/search/data-access/src/lib/utils/hit-to-search-result.util.ts
- libs/blog/search/ui-search-result/src/lib/search-result-item/search-result-item.component.html
- libs/blog/search/ui-search-result/src/lib/search-result-item/search-result-item.component.ts
- libs/blog/shared/types/src/lib/article-card.ts
Appended:
-date pipe
Changed:
-`mapHitToSearchResult`
-model
> fix(date-translations): appended pipe, changed model and mapper

- libs/blog/articles/ui-article-content/src/lib/article-content/article-content.component.scss
Changed:
`font-weight` property
> fix(article-contnent): changed font-weight property

- libs/blog/search/data-access/src/lib/utils/hit-to-search-result.util.ts
> fix(search-data-access): replaced value

- apps/blog/src/app/app.config.ts
- apps/blog/src/app/providers/skeleton-config-provider.ts
Changed:
-the color of skeletons from light to dark
> feat(blog): adjust skeletons color for dark mode (#154)

- libs/blog/ad-banner/ui/src/lib/ad-banner/ad-banner.component.html
> style(ad-banner): changed styles for tablets

- libs/blog/articles/ui-article-content/src/lib/article-content/article-content.component.scss
> style(article-content): changed styles to make content more visible

- libs/blog/articles/feature-article/src/lib/article-details/article-details-skeleton.component.ts
- libs/blog/articles/feature-article/src/lib/article-details/article-details.component.html
Appended:
-skeleton
Changed:
-placeholder
> feat(article-details): crated skeleton of table of contents and changed placeholder

- libs/blog/ad-banner/data-access/src/lib/state/ad-banner.store.ts
Changed:
-`ad-banner` hidden on init
> fix(ad-banner): banner hidden on init

- apps/blog/src/assets/i18n/en.json
- apps/blog/src/assets/i18n/pl.json
- libs/blog/newsletter/feature-newsletter/src/lib/feature-newsletter/newsletter.component.html
Changed:
-styles
-translations
> refactor(newsletter): content replaced, changed styles

- libs/blog/articles/feature-article/src/lib/article-details/article-details.component.ts
- libs/blog/articles/feature-list/src/lib/category-section-container/category-section-container.component.ts
- libs/blog/articles/ui-article-card/src/lib/components/article-compact-card/article-compact-card.component.ts
- libs/blog/articles/ui-article-card/src/lib/components/article-hero-card/article-hero-card.component.spec.ts
- libs/blog/articles/ui-article-card/src/lib/components/article-hero-card/article-hero-card.component.ts
- libs/blog/articles/ui-article-card/src/lib/components/article-horizontal-card/article-horizontal-card.component.ts
- libs/blog/articles/ui-article-card/src/lib/components/article-regular-card/article-regular-card.component.ts
- libs/blog/articles/ui-article-card/src/lib/ui-article-card/ui-article-card.component.ts
- libs/blog/articles/ui-article-content/src/lib/article-content/article-content.component.ts
- libs/blog/articles/ui-article-list-title/src/lib/ui-article-list-title/ui-article-list-title.component.ts
- libs/blog/articles/ui-table-of-contents/src/lib/table-of-contents/table-of-contents.component.ts
- libs/blog/layouts/ui-layouts/src/lib/footer/components/footer-logo.component.ts
- libs/blog/layouts/ui-layouts/src/lib/header/header.component.ts
- libs/blog/layouts/ui-navigation/src/lib/navigation/navigation.component.ts
- libs/blog/partners/ui-partners/src/lib/partners-list/partners-list.component.ts
- libs/blog/partners/ui-partners/src/lib/partners/partners.component.ts
- libs/blog/search/feature-search/src/lib/feature-search/search-dialog/search-dialog.component.ts
- libs/blog/search/ui-search-result/src/lib/search-result-item/search-result-item.component.ts
- libs/blog/shared/ui-avatar/src/lib/avatar.component.ts
- libs/blog/shared/ui-breadcrumb/src/lib/breadcrumb/breadcrumb.component.ts
- libs/blog/shared/ui-button/src/lib/button/button.component.ts
- libs/blog/shared/ui-card/src/lib/card.component.ts
> fix(client): access modifiers fix

- libs/blog/articles/feature-article/src/lib/article-details/article-details-skeleton.component.ts
Appended:
-share article skeleton
> feat(article-details-skeleton): section share article appended skeleton

- libs/blog/shared/ui-social-media-icons/src/lib/social-media-icon-item.component.ts
- libs/blog/shared/ui-social-media-icons/src/lib/social-media-icons.component.ts
Changed:
-translation structure in file
> fix(social-media-icons): bug fixed, translation moved to another file

- libs/blog/articles/feature-article/src/lib/article-details/article-details.component.html
- libs/blog/articles/feature-article/src/lib/article-share-icons/article-share-icons.component.ts
missing language in URL when sharing english articles
> fix(blog): sharing en articles

- libs/blog/ad-banner/ui/src/index.ts
- libs/blog/ad-banner/ui/src/lib/instances/al-indepth-banner.component.ts
- libs/blog/articles/feature-list/src/lib/articles-list-container.component.html
- libs/blog/articles/feature-list/src/lib/articles-list-container.component.ts
- libs/blog/home/feature-home/src/lib/home-page/home-page.component.html
- libs/blog/home/feature-home/src/lib/home-page/home-page.component.ts
> feat(client): move indepth banner to the indepth article section

- libs/blog-bff/articles/api/src/lib/utils.ts
precompiled languages seem broken in some cases
> fix(bff): shiki precompiled langs are not formatting properly
